CREATE TABLE CIRCUITS (

	CIRCUIT_ID INT NOT NULL,
	CIRCUIT_REF VARCHAR(30) NOT NULL,
	LOCATION VARCHAR(30) NOT NULL,
	COUNTRY VARCHAR(30) NOT NULL,
	LAT FLOAT(8),
	LONG FLOAT(8),
	ALT INT,
	URL VARCHAR(100),

	CONSTRAINT PK_CIRCUIT PRIMARY KEY(CIRCUIT_ID)

);

CREATE TABLE CONSTRUCTORS (
    CONSTRUCTOR_ID INT NOT NULL,
    CONSTRUCTOR_REF VARCHAR(50),
    NAME VARCHAR(50),
    NATIONALITY VARCHAR(50),
    URL VARCHAR(100),

    CONSTRAINT PK_CONSTRUCTORS PRIMARY KEY(CONSTRUCTOR_ID)

);

CREATE TABLE SEASONS (
	YEAR INT NOT NULL,
  URL VARCHAR(100),
  
	CONSTRAINT PK_YEAR PRIMARY KEY(YEAR)
);

CREATE TABLE STATUS (
	STATUS_ID INT NOT NULL,
  STATUS VARCHAR(50) NOT NULL,
  
	CONSTRAINT PK_STATUS PRIMARY KEY(STATUS_ID)
);

CREATE TABLE AIRPORTS (
	AIRPORTS_ID INT NOT NULL,
	IDENT VARCHAR(7),
	TYPE VARCHAR(15),
	NAME VARCHAR(80),
  	LAT_DEG NUMERIC(23,20),
  	LONG_DEG NUMERIC(23,20),
  	ELEV_FT INT,
	CONTINENT CHAR(2),
	ISO_COUNTRY CHAR(2),
	ISO_REGION CHAR(10),
	CITY VARCHAR(100),
	SCHEDULED_SERVICE VARCHAR(3),
	GPS_CODE VARCHAR(7),
  	IATA_CODE CHAR(3),
	LOCAL_CODE VARCHAR(7),
	HOME_LINK VARCHAR(200),
	WIKIPEDIA_LINK VARCHAR(200),
  	KEYWORDS VARCHAR(400),
  
	CONSTRAINT PK_AIRPORTS PRIMARY KEY(AIRPORTS_ID)

);


CREATE TABLE DRIVER (
	DRIVER_ID INT NOT NULL,
	DRIVER_REF VARCHAR(80) NOT NULL,
	NUMBER VARCHAR(4),
	CODE VARCHAR(5),
	FORENAME VARCHAR(80),
	SURNAME VARCHAR(80),
	DATE_OF_BIRTH DATE,
	NATIONALITY VARCHAR(80),
  URL VARCHAR(100),

	CONSTRAINT PK_DRIVER PRIMARY KEY(DRIVER_ID)

);

CREATE TABLE RACES (
	RACES_ID INT NOT NULL,
  	YEAR_SEASON INT,
  	ROUND INT,
  	CIRCIT_ID INT,
	NAME VARCHAR(40),
  	DATE DATE,
  	TIME TIME,
	URL VARCHAR(100),
  	FP1_DATE DATE,
	FP1_TIME TIME,
  	FP2_DATE DATE,
  	FP2_TIME TIME,
  	FP3_DATE DATE,
  	FP3_TIME TIME,
  	QUALI_DATE DATE,
	QUALI_TIME TIME,
	SPRINT_DATE DATE,
	SPRINT_TIME TIME,
	  	
	CONSTRAINT PK_RACES PRIMARY KEY(RACES_ID),
  	FOREIGN KEY (YEAR_SEASON) REFERENCES SEASONS (YEAR)
  
);


CREATE TABLE COUNTRIES (
	COUNTRIES_ID INT NOT NULL,
	CODE CHAR(2),
	NAME VARCHAR(100),
	CONTINENT CHAR(2),
	WIKIPEDIA_LINK VARCHAR(100),
	KEYWORDS VARCHAR(200),

	CONSTRAINT PK_COUNTRIES PRIMARY KEY(COUNTRIES_ID)

);

CREATE TABLE GEOCITIES15K (
	GEOCITIES15K INT NOT NULL,
	NAME VARCHAR(100),
	ASCII_NAME VARCHAR(100),
	ALTERNATE_NAMES VARCHAR(5000),
  	LAT NUMERIC(23,20),
  	LONG NUMERIC(23,20),
	FEATURE_CLASS CHAR(1),
	FEATURE_CODE VARCHAR(5),
	COUNTRY CHAR(2),
	CC2 VARCHAR(6),
  	ADMIN_1_CODE VARCHAR(100),
  	ADMIN_2_CODE VARCHAR(100),
  	ADMIN_3_CODE VARCHAR(100),
  	ADMIN_4_CODE VARCHAR(100),
  	POPULATION INT,
  	ELEVATION INT,
  	DEM INT,
  	TIME_ZONE VARCHAR(40),
  	MODIFICATION DATE,

	CONSTRAINT PK_GEOCITIES15K PRIMARY KEY(GEOCITIES15K)
);


CREATE TABLE DRIVER_STANDINGS (
	DRIVER_STANDINGS_ID INT NOT NULL,
	RACE_ID INT NOT NULL,
	DRIVER_ID SMALLINT NOT NULL,
	POINTS NUMERIC(6,3),
	POSITION SMALLINT,
	POSITION_TEXT CHAR(3),
	WINS SMALLINT,

	CONSTRAINT PK_DRIVER_STANDINGS PRIMARY KEY(DRIVER_STANDINGS_ID)

);

CREATE TABLE LAPTIMES (
	RACE_ID INT NOT NULL,
	DRIVER_ID INT NOT NULL,
	LAP INT NOT NULL,
	POSITION INT,
  	TIME TIME,
  	MILLISECONDS INT,

	CONSTRAINT PK_LAPTIMES PRIMARY KEY(RACE_ID, DRIVER_ID, LAP),
  	FOREIGN KEY (RACE_ID) REFERENCES RACES (RACES_ID),
  	FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID)
  
);

CREATE TABLE PITSTOPS (
	RACE_ID INT NOT NULL,
	DRIVER_ID INT NOT NULL,
	STOP INT NOT NULL,
	LAP INT,
	TIME TIME,
	LAT_DEG VARCHAR(15),
  	MILLISECONDS INT,

	CONSTRAINT PK_PITSTOPS PRIMARY KEY(RACE_ID, DRIVER_ID, STOP),
		FOREIGN KEY (RACE_ID) REFERENCES RACES (RACES_ID),
		FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID)
  
);
drop table qualifying ;
CREATE TABLE QUALIFYING (
	QUALIFYING_ID INT NOT NULL,
	RACE_ID INT,
	DRIVER_ID INT,
	CONSTRUCTOR_ID INT,
  	NUMBER INT,
	POSITION INT,
  	Q1 INTERVAL,
  	Q2 INTERVAL,
  	Q3 INTERVAL,

	CONSTRAINT PK_QUALIFYING PRIMARY KEY(QUALIFYING_ID),
  		FOREIGN KEY (RACE_ID) REFERENCES RACES (RACES_ID),
  		FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID),
  		FOREIGN KEY (CONSTRUCTOR_ID) REFERENCES CONSTRUCTORS (CONSTRUCTOR_ID)
  
);

drop table Results;
CREATE TABLE RESULTS (
	RESULTS_ID INT NOT NULL,
	RACE_ID INT,
	DRIVER_ID INT,
	CONSTRUCTOR_ID INT,
  	NUMBER INT,
  	GRID INT,
	POSITION INT,
	POSITION_TEXT VARCHAR(3),
	POSITION_ORDER INT,
	POINTS NUMERIC(6,2),
	LAPS INT,
	TIME INTERVAL,
  	MILLISECONDS INT,
  	FASTEST_LAP INT,
  	RANK INT,
  	FASTEST_LAP_TIME TIME,
  	FASTEST_LAP_SPEED NUMERIC(8,3),
	STATUS_ID INT,
  
  
	CONSTRAINT PK_RESULTS PRIMARY KEY(RESULTS_ID),
  		FOREIGN KEY (RACE_ID) REFERENCES RACES (RACES_ID),
  		FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID),
  		FOREIGN KEY (CONSTRUCTOR_ID) REFERENCES CONSTRUCTORS (CONSTRUCTOR_ID), 
  		FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID)
  
);

